// Dummy data for testing

export const dummyPlayers = [
  {
    id: 'player_1',
    name: 'Virat Kohli',
    profilePicture: 'https://via.placeholder.com/150',
    age: 35,
    phoneNumber: '+91 9876543210',
    basePoints: 100,
    status: 'available',
    teamId: null,
    soldPrice: null,
  },
  {
    id: 'player_2',
    name: 'Rohit Sharma',
    profilePicture: 'https://via.placeholder.com/150',
    age: 36,
    phoneNumber: '+91 9876543211',
    basePoints: 100,
    status: 'available',
    teamId: null,
    soldPrice: null,
  },
  {
    id: 'player_3',
    name: 'Jasprit Bumrah',
    profilePicture: 'https://via.placeholder.com/150',
    age: 30,
    phoneNumber: '+91 9876543212',
    basePoints: 100,
    status: 'available',
    teamId: null,
    soldPrice: null,
  },
  {
    id: 'player_4',
    name: 'KL Rahul',
    profilePicture: 'https://via.placeholder.com/150',
    age: 31,
    phoneNumber: '+91 9876543213',
    basePoints: 100,
    status: 'available',
    teamId: null,
    soldPrice: null,
  },
  {
    id: 'player_5',
    name: 'Hardik Pandya',
    profilePicture: 'https://via.placeholder.com/150',
    age: 30,
    phoneNumber: '+91 9876543214',
    basePoints: 100,
    status: 'available',
    teamId: null,
    soldPrice: null,
  },
  {
    id: 'player_6',
    name: 'Ravindra Jadeja',
    profilePicture: 'https://via.placeholder.com/150',
    age: 35,
    phoneNumber: '+91 9876543215',
    basePoints: 100,
    status: 'available',
    teamId: null,
    soldPrice: null,
  },
  {
    id: 'player_7',
    name: 'Shubman Gill',
    profilePicture: 'https://via.placeholder.com/150',
    age: 24,
    phoneNumber: '+91 9876543216',
    basePoints: 100,
    status: 'available',
    teamId: null,
    soldPrice: null,
  },
  {
    id: 'player_8',
    name: 'Mohammed Siraj',
    profilePicture: 'https://via.placeholder.com/150',
    age: 29,
    phoneNumber: '+91 9876543217',
    basePoints: 100,
    status: 'available',
    teamId: null,
    soldPrice: null,
  },
  {
    id: 'player_9',
    name: 'Rishabh Pant',
    profilePicture: 'https://via.placeholder.com/150',
    age: 26,
    phoneNumber: '+91 9876543218',
    basePoints: 100,
    status: 'available',
    teamId: null,
    soldPrice: null,
  },
  {
    id: 'player_10',
    name: 'Axar Patel',
    profilePicture: 'https://via.placeholder.com/150',
    age: 30,
    phoneNumber: '+91 9876543219',
    basePoints: 100,
    status: 'available',
    teamId: null,
    soldPrice: null,
  },
];

export const dummyTeams = [
  {
    id: 'team_1',
    name: 'Mumbai Indians',
    logo: 'https://via.placeholder.com/100',
    budget: 10000,
    color: '#004BA0',
  },
  {
    id: 'team_2',
    name: 'Chennai Super Kings',
    logo: 'https://via.placeholder.com/100',
    budget: 10000,
    color: '#FDB913',
  },
  {
    id: 'team_3',
    name: 'Royal Challengers',
    logo: 'https://via.placeholder.com/100',
    budget: 10000,
    color: '#EC1C24',
  },
  {
    id: 'team_4',
    name: 'Kolkata Knight Riders',
    logo: 'https://via.placeholder.com/100',
    budget: 10000,
    color: '#3A225D',
  },
];
